package main

import (
	"context"
	"errors"
	"log"
	"os"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURI = "amqp://guest:guest@localhost:5672/"

func main() {
	ctx := context.Background()
	env := rmq.NewEnvironment(brokerURI, nil)

	conn, err := env.NewConnection(ctx)
	if err != nil {
		panic(err)
	}
	defer func() {
		env.CloseConnections(context.Background())
	}()

	exInfo, err := conn.Management().DeclareExchange(ctx, &rmq.DirectExchangeSpecification{Name: "logs_direct"})
	if err != nil {
		panic(err)
	}

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsAutoDelete: true,
		IsExclusive:  true,
	})
	if err != nil {
		panic(err)
	}

	for _, s := range os.Args[1:] {
		log.Println("binding queue", qInfo.Name(), "to exchange", exInfo.Name(), "with routing key", s)

		_, err := conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
			SourceExchange:   exInfo.Name(),
			DestinationQueue: qInfo.Name(),
			BindingKey:       s,
		})
		if err != nil {
			panic(err)
		}
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		panic(err)
	}
	defer func() {
		consumer.Close(context.Background())
	}()

	log.Println("[*] waiting for logs...")
	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return
			}
			panic(err)
		}

		msg := delivery.Message()
		var body string

		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}

		log.Println("[x]", body)
		err = delivery.Accept(ctx)
		if err != nil {
			panic(err)
		}

	}
}
