package main

import (
	"context"
	"errors"
	"log"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

const brokerURL = "amqp://guest:guest@localhost:5672"

func main() {
	log.SetFlags(log.Lshortfile)

	ctx := context.Background()

	env := rmq.NewEnvironment(brokerURL, nil)

	conn, err := env.NewConnection(ctx)
	if err != nil {
		panic(err)
	}

	defer func() {
		env.CloseConnections(context.Background())
	}()

	exInfo, err := conn.Management().DeclareExchange(ctx, &rmq.FanOutExchangeSpecification{Name: "logs"})
	if err != nil {
		panic(err)
	}

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsExclusive:  true,
		IsAutoDelete: true,
	})
	if err != nil {
		panic(err)
	}

	// binding - the relationship b/w the exchange and the queue
	_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
		SourceExchange:   exInfo.Name(),
		DestinationQueue: qInfo.Name(),
		BindingKey:       "",
	})
	if err != nil {
		panic(err)
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		panic(err)
	}
	defer func() {
		consumer.Close(context.Background())
	}()

	log.Println("waiting for logs...")
	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return
			}
			panic(err)
		}

		msg := delivery.Message()
		var body string
		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}

		log.Println("[x]", string(body))
		err = delivery.Accept(ctx)
		if err != nil {
			panic(err)
		}
	}
}
