package main

import (
	"context"
	"errors"
	"log"
	"os"

	"github.com/joho/godotenv"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

func main() {
	log.SetFlags(log.Lshortfile)

	err := godotenv.Load("../.env")
	if err != nil {
		log.Fatalln("failed to load .env")
	}

	RMQ_URI := os.Getenv("RMQ_URI")

	///////////////////////////////////////////////////////
	ctx := context.Background()

	env := rmq.NewEnvironment(RMQ_URI, nil)

	conn, err := env.NewConnection(ctx)
	if err != nil {
		log.Fatalln("failed to open connection:", err)
	}
	defer env.CloseConnections(context.Background())

	exchangeInfo, err := conn.Management().DeclareExchange(ctx, &rmq.TopicExchangeSpecification{Name: "notifications"})
	if err != nil {
		log.Fatalln("failed to declare exchange:", err)
	}

	qInfo, err := conn.Management().DeclareQueue(ctx, &rmq.AutoGeneratedQueueSpecification{
		IsAutoDelete: true,
		IsExclusive:  true,
	})
	if err != nil {
		log.Fatalln("failed to declare queue:", err)
	}

	_, err = conn.Management().Bind(ctx, &rmq.ExchangeToQueueBindingSpecification{
		SourceExchange:   exchangeInfo.Name(),
		DestinationQueue: qInfo.Name(),
		BindingKey:       "notifications.sms",
	})
	if err != nil {
		log.Fatalln("failed to bind queue:", err)
	}

	consumer, err := conn.NewConsumer(ctx, qInfo.Name(), nil)
	if err != nil {
		log.Fatalln("failed to create consumer:", err)
	}
	defer consumer.Close(context.Background())

	for {
		delivery, err := consumer.Receive(ctx)
		if err != nil {
			if errors.Is(err, context.Canceled) {
				return
			}
			log.Fatalln(err)
		}

		msg := delivery.Message()
		var body string
		if len(msg.Data) > 0 {
			body = string(msg.Data[0])
		}

		log.Println("[x]", body)

		err = delivery.Accept(ctx)
		if err != nil {
			log.Fatalln(err)
		}

	}
}
